// Generated by build.js — do not edit. Rebuild with: node build.js <chrome|firefox>

(() => {
  // shared/constants.js
  var suggestionSources = ["tab", "history", "bookmark"];

  // shared/url.js
  var urlSchemes = /* @__PURE__ */ new Set([
    "http",
    "https",
    "file",
    "about",
    "chrome",
    "helium"
  ]);
  var blockedUrlSchemes = /* @__PURE__ */ new Set([
    "javascript",
    "data",
    "vbscript",
    "chrome-extension",
    "edge",
    "moz-extension",
    "view-source"
  ]);
  function isValidHostname(host) {
    if (!host) return false;
    const lower = host.toLowerCase();
    if (lower === "localhost") return true;
    if (/^\d{1,3}(\.\d{1,3}){3}$/.test(lower)) {
      return lower.split(".").every((o) => {
        const n = parseInt(o, 10);
        return n >= 0 && n <= 255 && String(n) === o;
      });
    }
    const labels = lower.split(".");
    if (labels.length < 2) return false;
    for (const label of labels) {
      if (!label || label.length > 63) return false;
      if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(label)) return false;
    }
    const tld = labels[labels.length - 1];
    if (tld.length < 2 || !/^[a-z]{2,63}$/.test(tld)) return false;
    if (/^\d+$/.test(tld)) return false;
    return true;
  }
  function normalizeUrl(raw) {
    if (typeof raw !== "string") return null;
    const url = raw.trim();
    if (!url || /\s/.test(url)) return null;
    if (/^localhost(:\d+)?(\/.*)?$/i.test(url) || /^127\.0\.0\.1(:\d+)?(\/.*)?$/i.test(url) || /^0\.0\.0\.0(:\d+)?(\/.*)?$/i.test(url))
      return "http://" + url;
    if (url.startsWith("//")) {
      try {
        const u = new URL("https:" + url);
        if (!isValidHostname(u.hostname)) return null;
        return "https:" + url;
      } catch {
        return null;
      }
    }
    const m = url.match(/^([a-zA-Z][a-zA-Z0-9+.-]*):/);
    if (!m) {
      const hostPart = url.split(/[:/?#]/)[0];
      if (!isValidHostname(hostPart)) return null;
      try {
        const u = new URL("https://" + url);
        if (!isValidHostname(u.hostname)) return null;
      } catch {
        return null;
      }
      return "https://" + url;
    }
    const scheme = m[1].toLowerCase();
    if (urlSchemes.has(scheme)) {
      if (scheme === "http" || scheme === "https") {
        try {
          const u = new URL(url);
          if (u.hostname && !isValidHostname(u.hostname)) return null;
        } catch {
          return null;
        }
      }
      return url;
    }
    if (blockedUrlSchemes.has(scheme)) return null;
    const rest = url.slice(m[0].length);
    if (/^(\d+)(\/.*)?$/.test(rest)) return "https://" + url;
    return null;
  }

  // background/handlers.js
  function clampCount(count, max = 20) {
    const n = Math.floor(count);
    return Number.isFinite(n) ? Math.min(max, Math.max(1, n)) : 1;
  }
  async function getSuggestionSources() {
    try {
      const stored = await chrome.storage.sync.get("settings");
      const sources = stored.settings && stored.settings.suggestionSources;
      if (Array.isArray(sources)) {
        return sources.filter((s) => suggestionSources.includes(s));
      }
    } catch (err) {
      console.debug("[jari] Failed to get suggestion sources:", err);
    }
    return suggestionSources.slice();
  }
  var handlers = {
    createTab: async (_, { url } = {}) => {
      const target = url === void 0 ? void 0 : normalizeUrl(url);
      if (url !== void 0 && !target) return { ok: false };
      const tab = await chrome.tabs.create(target ? { url: target } : {});
      return tab ? { ok: true, id: tab.id } : { ok: false };
    },
    navigate: async (sender, { url } = {}) => {
      const target = normalizeUrl(url);
      if (!target || !sender.tab || !sender.tab.id) return { ok: false };
      await chrome.tabs.update(sender.tab.id, { url: target });
      return { ok: true };
    },
    closeTab: async (sender, { count = 1 } = {}) => {
      const tab = sender.tab;
      if (!tab || !tab.id) return { ok: false };
      const tabs = await chrome.tabs.query({ currentWindow: true });
      const index = tabs.findIndex((t) => t.id === tab.id);
      if (index === -1) return { ok: false };
      const ids = tabs.slice(index, index + clampCount(count)).map((t) => t.id);
      await chrome.tabs.remove(ids);
      return { ok: true, closed: ids.length };
    },
    restoreTab: async (_, { count = 1 } = {}) => {
      let sessions;
      try {
        sessions = await chrome.sessions.getRecentlyClosed();
      } catch (err) {
        console.debug("[jari] Failed to get recently closed sessions:", err);
        return { ok: true };
      }
      const tabs = (sessions || []).filter((s) => s.tab && s.tab.sessionId);
      for (let i = 0; i < Math.min(clampCount(count), tabs.length); i++) {
        try {
          await chrome.sessions.restore(tabs[i].tab.sessionId);
        } catch {
          break;
        }
      }
      return { ok: true };
    },
    previousTab: async (sender, { count = 1 } = {}) => {
      return switchTab(sender.tab, -clampCount(count));
    },
    nextTab: async (sender, { count = 1 } = {}) => {
      return switchTab(sender.tab, clampCount(count));
    },
    splitOrMerge: async (sender) => {
      const tab = sender.tab;
      if (!tab || !tab.id) return { ok: false };
      const myTabs = await chrome.tabs.query({ windowId: tab.windowId });
      if (myTabs.length > 1) {
        await chrome.windows.create({ tabId: tab.id });
        return { ok: true, split: true };
      }
      const windows = await chrome.windows.getAll({ populate: true });
      const others = windows.filter((win) => win.id !== tab.windowId).map((win) => {
        const wtab = win.tabs && win.tabs.length ? win.tabs.find((t) => t.active) || win.tabs[0] : null;
        return {
          windowId: win.id,
          title: wtab && wtab.title ? wtab.title : "Window",
          url: `${win.tabs ? win.tabs.length : 0} tabs`
        };
      });
      if (others.length === 0) return { ok: true, needMerge: false };
      if (others.length === 1) {
        const targetWindowId = others[0].windowId;
        await chrome.tabs.move(tab.id, { windowId: targetWindowId, index: -1 });
        const tabs = await chrome.tabs.query({ windowId: targetWindowId });
        const last = tabs[tabs.length - 1];
        if (last) {
          try {
            await focusWindow(targetWindowId);
          } catch (err) {
            console.error("[jari] splitOrMerge auto-merge window focus failed", err);
          }
          await chrome.tabs.update(last.id, { active: true });
        }
        return { ok: true, autoMerged: true };
      }
      return {
        ok: true,
        needMerge: true,
        ownTabId: tab.id,
        ownWindowId: tab.windowId,
        tabs: others
      };
    },
    mergeTab: async (sender, { targetWindowId } = {}) => {
      const tab = sender.tab;
      if (!tab || !tab.id || !targetWindowId) return { ok: false };
      await chrome.tabs.move(tab.id, { windowId: targetWindowId, index: -1 });
      const tabs = await chrome.tabs.query({ windowId: targetWindowId });
      const last = tabs[tabs.length - 1];
      if (last) {
        try {
          await focusWindow(targetWindowId);
        } catch (err) {
          console.error("[jari] mergeTab window focus failed", err);
        }
        await chrome.tabs.update(last.id, { active: true });
      }
      return { ok: true };
    },
    moveTabLeft: async (sender) => {
      const tab = sender.tab;
      if (tab && tab.id) {
        await chrome.tabs.move(tab.id, { index: Math.max(0, tab.index - 1) });
      }
      return { ok: true };
    },
    firstTab: async () => {
      const tabs = await chrome.tabs.query({ currentWindow: true });
      if (tabs.length) await chrome.tabs.update(tabs[0].id, { active: true });
      return { ok: true };
    },
    lastTab: async () => {
      const tabs = await chrome.tabs.query({ currentWindow: true });
      if (tabs.length)
        await chrome.tabs.update(tabs[tabs.length - 1].id, { active: true });
      return { ok: true };
    },
    moveTabRight: async (sender) => {
      const tab = sender.tab;
      if (tab && tab.id) {
        await chrome.tabs.move(tab.id, { index: tab.index + 1 });
      }
      return { ok: true };
    },
    duplicateTab: async (sender) => {
      if (sender.tab && sender.tab.id) {
        await chrome.tabs.duplicate(sender.tab.id);
      }
      return { ok: true };
    },
    togglePin: async (sender) => {
      const tab = sender.tab;
      if (tab && tab.id) {
        await chrome.tabs.update(tab.id, { pinned: !tab.pinned });
      }
      return { ok: true };
    },
    toggleMute: async (sender) => {
      const tab = sender.tab;
      if (tab && tab.id) {
        const muted = !!(tab.mutedInfo && tab.mutedInfo.muted);
        await chrome.tabs.update(tab.id, { muted: !muted });
      }
      return { ok: true };
    },
    reloadTab: async (sender, { bypassCache = false } = {}) => {
      if (sender.tab && sender.tab.id) {
        await chrome.tabs.reload(sender.tab.id, { bypassCache });
      }
      return { ok: true };
    },
    historyBack: async (sender) => goHistory(sender.tab, -1),
    historyForward: async (sender) => goHistory(sender.tab, 1),
    listTabs: async () => {
      const tabs = await chrome.tabs.query({});
      return tabs.map((tab) => ({
        id: tab.id,
        windowId: tab.windowId,
        title: tab.title || "",
        url: tab.url || "",
        active: !!tab.active,
        lastAccessed: tab.lastAccessed || 0,
        audible: !!tab.audible
      }));
    },
    suggest: async (_, { query = "" } = {}) => {
      const q = query.trim().toLowerCase();
      const qRaw = query.trim();
      const items = [];
      const seen = /* @__PURE__ */ new Set();
      function push(title, url, source, extra = {}) {
        if (!url || seen.has(url)) return;
        seen.add(url);
        items.push({ title: title || url, url, source, ...extra });
      }
      const sources = await getSuggestionSources();
      if (sources.includes("tab")) {
        try {
          const tabs = await chrome.tabs.query({});
          tabs.sort((a, b) => (b.lastAccessed || 0) - (a.lastAccessed || 0));
          for (const tab of tabs) push(tab.title || "", tab.url || "", "tab", { lastAccessed: tab.lastAccessed || 0, audible: !!tab.audible });
        } catch (err) {
          console.debug("[jari] Tab search failed:", err);
        }
      }
      if (!q) {
        if (sources.includes("history")) {
          try {
            const recents = await chrome.history.search({ text: "", maxResults: 20, startTime: 0 });
            recents.sort((a, b) => (b.lastVisitTime || 0) - (a.lastVisitTime || 0));
            for (const item of recents.slice(0, 8)) push(item.title, item.url, "history", { visitCount: item.visitCount || 0, lastVisit: item.lastVisitTime || 0, typedCount: item.typedCount || 0 });
          } catch (err) {
            console.debug("[jari] Recent history failed:", err);
          }
        }
      } else {
        if (sources.includes("history")) {
          try {
            const results = await chrome.history.search({
              text: qRaw,
              maxResults: 24,
              startTime: 0
            });
            for (const item of results) push(item.title, item.url, "history", { visitCount: item.visitCount || 0, lastVisit: item.lastVisitTime || 0, typedCount: item.typedCount || 0 });
          } catch (err) {
            console.debug("[jari] History search failed:", err);
          }
        }
        if (sources.includes("bookmark")) {
          try {
            const bms = await chrome.bookmarks.search(qRaw);
            for (const bm of bms) if (bm.url) push(bm.title, bm.url, "bookmark", { dateAdded: bm.dateAdded || 0 });
          } catch (err) {
            console.debug("[jari] Bookmark search failed:", err);
          }
        }
      }
      return items.slice(0, 50);
    },
    search: async (sender, { query = "", newTab = true } = {}) => {
      const text = query.trim();
      if (!text) return { ok: false };
      if (typeof chrome.search?.query === "function") {
        await chrome.search.query({
          text,
          disposition: newTab ? "NEW_TAB" : "CURRENT_TAB"
        });
        return { ok: true };
      }
      const url = "https://www.google.com/search?q=" + encodeURIComponent(text);
      if (newTab) {
        await chrome.tabs.create({ url });
      } else if (sender.tab && sender.tab.id) {
        await chrome.tabs.update(sender.tab.id, { url });
      }
      return { ok: true };
    },
    activateTab: async (_, { id } = {}) => {
      if (!id) return { ok: false };
      let windowId = null;
      try {
        const tab = await chrome.tabs.get(id);
        windowId = tab && tab.windowId;
      } catch {
      }
      if (id) {
        try {
          await chrome.tabs.update(id, { active: true });
        } catch (err) {
          return { ok: false, error: String(err) };
        }
      }
      if (windowId) {
        try {
          await focusWindow(windowId);
        } catch (err) {
          console.error("[jari] activateTab window focus failed", err);
        }
      }
      return { ok: true };
    },
    zoomBy: async (sender, { delta = 0 } = {}) => {
      const tab = sender.tab;
      if (!tab || !tab.id || typeof chrome.tabs.getZoom !== "function" || typeof chrome.tabs.setZoom !== "function") {
        return { ok: false };
      }
      const current = await chrome.tabs.getZoom(tab.id);
      const next = Math.min(5, Math.max(0.25, current + delta));
      await chrome.tabs.setZoom(tab.id, next);
      return { ok: true, zoom: next };
    },
    openInBackgroundTab: async (_, { url } = {}) => {
      const target = normalizeUrl(url);
      if (!target) return { ok: false };
      await chrome.tabs.create({ url: target, active: false });
      return { ok: true };
    },
    openInForegroundTab: async (_, { url } = {}) => {
      const target = normalizeUrl(url);
      if (!target) return { ok: false };
      await chrome.tabs.create({ url: target, active: true });
      return { ok: true };
    },
    openOptions: async () => {
      await chrome.runtime.openOptionsPage();
      return { ok: true };
    },
    openExtensions: async () => {
      const urls = ["chrome://extensions", "about:addons", "edge://extensions"];
      for (const url of urls) {
        try {
          await chrome.tabs.create({ url });
          return { ok: true };
        } catch {
        }
      }
      return { ok: false };
    }
  };
  async function goHistory(tab, delta) {
    if (!tab || !tab.id) return { ok: false };
    const method = delta < 0 ? "goBack" : "goForward";
    if (typeof chrome.tabs[method] === "function") {
      try {
        await chrome.tabs[method](tab.id);
      } catch {
        return { ok: true };
      }
    }
    return { ok: true };
  }
  async function switchTab(current, delta) {
    if (!current || !current.id) return { ok: false };
    const tabs = await chrome.tabs.query({ currentWindow: true });
    if (tabs.length < 2) return { ok: false };
    const index = tabs.findIndex((tab) => tab.id === current.id);
    if (index === -1) return { ok: false };
    const nextIndex = ((index + delta) % tabs.length + tabs.length) % tabs.length;
    await chrome.tabs.update(tabs[nextIndex].id, { active: true });
    return { ok: true };
  }
  async function focusWindow(windowId) {
    const win = await chrome.windows.get(windowId);
    if (win && win.state === "minimized") {
      await chrome.windows.update(windowId, { focused: true, state: "normal" });
    } else {
      await chrome.windows.update(windowId, { focused: true });
    }
  }

  // background/main.js
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    const handler = handlers[message && message.action];
    if (!handler) return;
    const result = handler(sender, message || {});
    if (result && typeof result.then === "function") {
      result.then(
        (value) => sendResponse(value || { ok: true }),
        (err) => {
          console.error(`[jari] ${message.action} failed`, err);
          sendResponse({ ok: false, error: String(err) });
        }
      );
      return true;
    }
    sendResponse(result || { ok: true });
  });
})();
