// Generated by build.js — do not edit. Rebuild with: node build.js <chrome|firefox>

(() => {
  // shared/constants.js
  var suggestionSources = ["tab", "history", "bookmark"];
  var maxResultsDefault = 50;
  var maxResultsMin = 5;
  var maxResultsMax = 100;
  function clampMaxResults(n) {
    const v = Math.floor(n);
    if (!Number.isFinite(v)) return maxResultsDefault;
    return Math.min(maxResultsMax, Math.max(maxResultsMin, v));
  }

  // shared/search-engines.js
  var SEARCH_ENGINE_DEFAULTS = [
    { keyword: "g", url: "https://www.google.com/search?q=%s" },
    { keyword: "yt", url: "https://www.youtube.com/results?search_query=%s" },
    { keyword: "gh", url: "https://github.com/search?q=%s" },
    { keyword: "wiki", url: "https://en.wikipedia.org/wiki/Special:Search?search=%s" },
    { keyword: "chat", url: "https://chatgpt.com/?q=%s" }
  ];
  var MAX_SEARCH_ENGINES = 20;
  var SEARCH_KEYWORD_RE = /^[a-z0-9_]{1,16}$/;
  var SEARCH_ENGINE_URL_MAX = 500;
  var RESERVED_ENGINE_KEYWORDS = ["t"];
  function searchEngineDefaults() {
    return SEARCH_ENGINE_DEFAULTS.map((e) => ({ ...e }));
  }
  function validateSearchEngine(entry) {
    if (!entry || typeof entry !== "object") return "Engine must have a keyword and URL.";
    const keyword = String(entry.keyword || "").toLowerCase();
    if (!SEARCH_KEYWORD_RE.test(keyword)) {
      return "Keyword must be 1-16 letters, digits, or underscores.";
    }
    if (RESERVED_ENGINE_KEYWORDS.includes(keyword)) {
      return `Keyword "${keyword}" is reserved for tab search.`;
    }
    const url = String(entry.url || "").trim();
    if (!/^https?:\/\//i.test(url)) {
      return "URL must start with http:// or https://.";
    }
    if (url.length > SEARCH_ENGINE_URL_MAX) {
      return `URL must be ${SEARCH_ENGINE_URL_MAX} characters or fewer.`;
    }
    if (!url.includes("%s")) {
      return "URL must contain %s where the query goes.";
    }
    return null;
  }
  function normalizeSearchEngines(raw) {
    if (!Array.isArray(raw)) return searchEngineDefaults();
    const seen = /* @__PURE__ */ new Set();
    const out = [];
    for (const entry of raw) {
      if (out.length >= MAX_SEARCH_ENGINES) break;
      if (validateSearchEngine(entry)) continue;
      const keyword = String(entry.keyword).toLowerCase();
      if (seen.has(keyword)) continue;
      seen.add(keyword);
      out.push({ keyword, url: String(entry.url).trim() });
    }
    return out.length > 0 ? out : searchEngineDefaults();
  }
  function normalizeDefaultEngine(raw, engines) {
    const list = Array.isArray(engines) && engines.length > 0 ? engines : searchEngineDefaults();
    const keyword = String(raw || "").toLowerCase();
    if (list.some((e) => e && e.keyword === keyword)) return keyword;
    return list[0].keyword;
  }
  function buildEngineUrl(engines, keyword, query) {
    const kw = String(keyword || "").toLowerCase();
    const engine = (engines || []).find((e) => e && e.keyword === kw);
    if (!engine) return null;
    return String(engine.url).replaceAll("%s", encodeURIComponent(query));
  }

  // shared/url.js
  var urlSchemes = /* @__PURE__ */ new Set([
    "http",
    "https",
    "file",
    "about",
    "chrome",
    "helium"
  ]);
  var blockedUrlSchemes = /* @__PURE__ */ new Set([
    "javascript",
    "data",
    "vbscript",
    "chrome-extension",
    "edge",
    "moz-extension",
    "view-source"
  ]);
  var fileExtensionDenylist = /* @__PURE__ */ new Set([
    "js",
    "ts",
    "jsx",
    "tsx",
    "mjs",
    "cjs",
    "json",
    "css",
    "scss",
    "less",
    "html",
    "htm",
    "md",
    "markdown",
    "txt",
    "csv",
    "xml",
    "yaml",
    "yml",
    "toml",
    "ini",
    "conf",
    "config",
    "sh",
    "bash",
    "zsh",
    "fish",
    "py",
    "rb",
    "php",
    "java",
    "c",
    "cpp",
    "h",
    "hpp",
    "cs",
    "go",
    "rs",
    "swift",
    "kt",
    "kts",
    "dart",
    "vue",
    "svelte",
    "astro",
    "lua",
    "pl",
    "pm",
    "r",
    "sql",
    "db",
    "sqlite",
    "log",
    "lock",
    "env",
    "gitignore",
    "dockerignore",
    "gradle",
    "makefile",
    "cmake"
  ]);
  var knownTlds = new Set(
    `
  aaa aarp abb abbott abbvie abc able abogado abudhabi ac academy accenture
  accountant accountants aco actor ad ads adult ae aeg aero aetna af
  afl africa ag agakhan agency ai aig airbus airforce airtel akdn al
  alibaba alipay allfinanz allstate ally alsace alstom am amazon americanexpress americanfamily amex
  amfam amica amsterdam analytics android anquan anz ao aol apartments app apple
  aq aquarelle ar arab aramco archi army arpa art arte as asda
  asia associates at athleta attorney au auction audi audible audio auspost author
  auto autos aw aws ax axa az azure ba baby baidu banamex
  band bank bar barcelona barclaycard barclays barefoot bargains baseball basketball bauhaus bayern
  bb bbc bbt bbva bcg bcn bd be beats beauty beer berlin
  best bestbuy bet bf bg bh bharti bi bible bid bike bing
  bingo bio biz bj black blackfriday blockbuster blog bloomberg blue bm bms
  bmw bn bnpparibas bo boats boehringer bofa bom bond boo book booking
  bosch bostik boston bot boutique box br bradesco bridgestone broadway broker brother
  brussels bs bt build builders business buy buzz bv bw by bz
  bzh ca cab cafe cal call calvinklein cam camera camp canon capetown
  capital capitalone car caravan cards care career careers cars casa case cash
  casino cat catering catholic cba cbn cbre cc cd center ceo cern
  cf cfa cfd cg ch chanel channel charity chase chat cheap chintai
  christmas chrome church ci cipriani circle cisco citadel citi citic city ck
  cl claims cleaning click clinic clinique clothing cloud club clubmed cm cn
  co coach codes coffee college cologne com commbank community company compare computer
  comsec condos construction consulting contact contractors cooking cool coop corsica country coupon
  coupons courses cpa cr credit creditcard creditunion cricket crown crs cruise cruises
  cu cuisinella cv cw cx cy cymru cyou cz dad dance data
  date dating datsun day dclk dds de deal dealer deals degree delivery
  dell deloitte delta democrat dental dentist desi design dev dhl diamonds diet
  digital direct directory discount discover dish diy dj dk dm dnp do
  docs doctor dog domains dot download drive dtv dubai dupont durban dvag
  dvr dz earth eat ec eco edeka edu education ee eg email
  emerck energy engineer engineering enterprises epson equipment er ericsson erni es esq
  estate et eu eurovision eus events exchange expert exposed express extraspace fage
  fail fairwinds faith family fan fans farm farmers fashion fast fedex feedback
  ferrari ferrero fi fidelity fido film final finance financial fire firestone firmdale
  fish fishing fit fitness fj fk flickr flights flir florist flowers fly
  fm fo foo food football ford forex forsale forum foundation fox fr
  free fresenius frl frogans frontier ftr fujitsu fun fund furniture futbol fyi
  ga gal gallery gallo gallup game games gap garden gay gb gbiz
  gd gdn ge gea gent genting george gf gg ggee gh gi
  gift gifts gives giving gl glass gle global globo gm gmail gmbh
  gmo gmx gn godaddy gold goldpoint golf goodyear goog google gop got
  gov gp gq gr grainger graphics gratis green gripe grocery group gs
  gt gu gucci guge guide guitars guru gw gy hair hamburg hangout
  haus hbo hdfc hdfcbank health healthcare help helsinki here hermes hiphop hisamitsu
  hitachi hiv hk hkt hm hn hockey holdings holiday homedepot homegoods homes
  homesense honda horse hospital host hosting hot hotels hotmail house how hr
  hsbc ht hu hughes hyatt hyundai ibm icbc ice icu id ie
  ieee ifm ikano il im imamat imdb immo immobilien in inc industries
  infiniti info ing ink institute insurance insure int international intuit investments io
  ipiranga iq ir irish is ismaili ist istanbul it itau itv jaguar
  java jcb je jeep jetzt jewelry jio jll jm jmp jnj jo
  jobs joburg jot joy jp jpmorgan jprs juegos juniper kaufen kddi ke
  kerryhotels kerryproperties kfh kg kh ki kia kids kim kindle kitchen kiwi
  km kn koeln komatsu kosher kp kpmg kpn kr krd kred kuokgroup
  kw ky kyoto kz la lacaixa lamborghini lamer land landrover lanxess lasalle
  lat latino latrobe law lawyer lb lc lds lease leclerc lefrak legal
  lego lexus lgbt li lidl life lifeinsurance lifestyle lighting like lilly limited
  limo lincoln link live living lk llc llp loan loans locker locus
  lol london lotte lotto love lpl lplfinancial lr ls lt ltd ltda
  lu lundbeck luxe luxury lv ly ma madrid maif maison makeup man
  management mango map market marketing markets marriott marshalls mattel mba mc mckinsey
  md me med media meet melbourne meme memorial men menu merck merckmsd
  mg mh miami microsoft mil mini mint mit mitsubishi mk ml mlb
  mls mm mma mn mo mobi mobile moda moe moi mom monash
  money monster mormon mortgage moscow moto motorcycles mov movie mp mq mr
  ms msd mt mtn mtr mu museum music mv mw mx my
  mz na nab nagoya name navy nba nc ne nec net netbank
  netflix network neustar new news next nextdirect nexus nf nfl ng ngo
  nhk ni nico nike nikon ninja nissan nissay nl no nokia norton
  now nowruz nowtv np nr nra nrw ntt nu nyc nz obi
  observer office okinawa olayan olayangroup ollo om omega one ong onl online
  ooo open oracle orange org organic origins osaka otsuka ott ovh pa
  page panasonic paris pars partners parts party pay pccw pe pet pf
  pfizer pg ph pharmacy phd philips phone photo photography photos physio pics
  pictet pictures pid pin ping pink pioneer pizza pk pl place play
  playstation plumbing plus pm pn pnc pohl poker politie porn post pr
  praxi press prime pro prod productions prof progressive promo properties property protection
  pru prudential ps pt pub pw pwc py qa qpon quebec quest
  racing radio re read realestate realtor realty recipes red redumbrella rehab reise
  reisen reit reliance ren rent rentals repair report republican rest restaurant review
  reviews rexroth rich richardli ricoh ril rio rip ro rocks rodeo rogers
  room rs rsvp ru rugby ruhr run rw rwe ryukyu sa saarland
  safe safety sakura sale salon samsclub samsung sandvik sandvikcoromant sanofi sap sarl
  sas save saxo sb sbi sbs sc scb schaeffler schmidt scholarships school
  schule schwarz science scot sd se search seat secure security seek select
  sener services seven sew sex sexy sfr sg sh shangrila sharp shell
  shia shiksha shoes shop shopping shouji show si silk sina singles site
  sj sk ski skin sky skype sl sling sm smart smile sn
  sncf so soccer social softbank software sohu solar solutions song sony soy
  spa space sport spot sr srl ss st stada staples star statebank
  statefarm stc stcgroup stockholm storage store stream studio study style su sucks
  supplies supply support surf surgery suzuki sv swatch swiss sx sy sydney
  systems sz tab taipei talk taobao target tatamotors tatar tattoo tax taxi
  tc tci td tdk team tech technology tel temasek tennis teva tf
  tg th thd theater theatre tiaa tickets tienda tips tires tirol tj
  tjmaxx tjx tk tkmaxx tl tm tmall tn to today tokyo tools
  top toray toshiba total tours town toyota toys tr trade trading training
  travel travelers travelersinsurance trust trv tt tube tui tunes tushu tv tvs
  tw tz ua ubank ubs ug uk unicom university uno uol ups
  us uy uz va vacations vana vanguard vc ve vegas ventures verisign
  versicherung vet vg vi viajes video vig viking villas vin vip virgin
  visa vision viva vivo vlaanderen vn vodka volvo vote voting voto voyage
  vu wales walmart walter wang wanggou watch watches weather weatherchannel web webcam
  weber website wed wedding weibo weir wf whoswho wien wiki williamhill win
  windows wine winners wme woodside work works world wow ws wtc wtf
  xbox xerox xihuan xin xn--11b4c3d xn--1ck2e1b xn--1qqw23a xn--2scrj9c xn--30rr7y xn--3bst00m xn--3ds443g xn--3e0b707e
  xn--3hcrj9c xn--3pxu8k xn--42c2d9a xn--45br5cyl xn--45brj9c xn--45q11c xn--4dbrk0ce xn--4gbrim xn--54b7fta0cc xn--55qw42g xn--55qx5d xn--5su34j936bgsg
  xn--5tzm5g xn--6frz82g xn--6qq986b3xl xn--80adxhks xn--80ao21a xn--80aqecdr1a xn--80asehdb xn--80aswg xn--8y0a063a xn--90a3ac xn--90ae xn--90ais
  xn--9dbq2a xn--9et52u xn--9krt00a xn--b4w605ferd xn--bck1b9a5dre4c xn--c1avg xn--c2br7g xn--cck2b3b xn--cckwcxetd xn--cg4bki xn--clchc0ea0b2g2a9gcd xn--czr694b
  xn--czrs0t xn--czru2d xn--d1acj3b xn--d1alf xn--e1a4c xn--eckvdtc9d xn--efvy88h xn--fct429k xn--fhbei xn--fiq228c5hs xn--fiq64b xn--fiqs8s
  xn--fiqz9s xn--fjq720a xn--flw351e xn--fpcrj9c3d xn--fzc2c9e2c xn--fzys8d69uvgm xn--g2xx48c xn--gckr3f0f xn--gecrj9c xn--gk3at1e xn--h2breg3eve xn--h2brj9c
  xn--h2brj9c8c xn--hxt814e xn--i1b6b1a6a2e xn--imr513n xn--io0a7i xn--j1aef xn--j1amh xn--j6w193g xn--jlq480n2rg xn--jvr189m xn--kcrx77d1x4a xn--kprw13d
  xn--kpry57d xn--kput3i xn--l1acc xn--lgbbat1ad8j xn--mgb9awbf xn--mgba3a3ejt xn--mgba3a4f16a xn--mgba7c0bbn0a xn--mgbaam7a8h xn--mgbab2bd xn--mgbah1a3hjkrd xn--mgbai9azgqp6j
  xn--mgbayh7gpa xn--mgbbh1a xn--mgbbh1a71e xn--mgbc0a9azcg xn--mgbca7dzdo xn--mgbcpq6gpa1a xn--mgberp4a5d4ar xn--mgbgu82a xn--mgbi4ecexp xn--mgbpl2fh xn--mgbt3dhd xn--mgbtx2b
  xn--mgbx4cd0ab xn--mix891f xn--mk1bu44c xn--mxtq1m xn--ngbc5azd xn--ngbe9e0a xn--ngbrx xn--node xn--nqv7f xn--nqv7fs00ema xn--nyqy26a xn--o3cw4h
  xn--ogbpf8fl xn--otu796d xn--p1acf xn--p1ai xn--pgbs0dh xn--pssy2u xn--q7ce6a xn--q9jyb4c xn--qcka1pmc xn--qxa6a xn--qxam xn--rhqv96g
  xn--rovu88b xn--rvc1e0am3e xn--s9brj9c xn--ses554g xn--t60b56a xn--tckwe xn--tiq49xqyj xn--unup4y xn--vermgensberater-ctb xn--vermgensberatung-pwb xn--vhquv xn--vuq861b
  xn--w4r85el8fhu5dnra xn--w4rs40l xn--wgbh1c xn--wgbl6a xn--xhq521b xn--xkc2al3hye2a xn--xkc2dl3a5ee0h xn--y9a3aq xn--yfro4i67o xn--ygbi2ammx xn--zfr164b xxx
  xyz yachts yahoo yamaxun yandex ye yodobashi yoga yokohama you youtube yt
  yun za zappos zara zero zip zm zone zuerich zw
  `.trim().split(/\s+/)
  );
  function isValidHostname(host) {
    if (!host) return false;
    let lower = host.toLowerCase();
    if (lower.startsWith("[") && lower.endsWith("]")) lower = lower.slice(1, -1);
    if (lower === "localhost") return true;
    if (/^\d{1,3}(\.\d{1,3}){3}$/.test(lower)) {
      return lower.split(".").every((o) => {
        const n = parseInt(o, 10);
        return n >= 0 && n <= 255 && String(n) === o;
      });
    }
    if (/^[0-9a-f:]+$/i.test(lower) && lower.includes(":")) {
      try {
        if (typeof URL !== "undefined") new URL(`http://[${lower}]/`);
        return true;
      } catch {
        return false;
      }
    }
    const labels = lower.split(".");
    if (labels.length < 2) return false;
    for (const label of labels) {
      if (!label || label.length > 63) return false;
      if (!/^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(label)) return false;
    }
    const tld = labels[labels.length - 1];
    if (/^xn--[a-z0-9-]{1,59}$/.test(tld)) return true;
    if (tld.length < 2 || !/^[a-z]{2,63}$/.test(tld)) return false;
    return true;
  }
  function isBareNavigableHostname(host) {
    if (!isValidHostname(host)) return false;
    let lower = host.toLowerCase();
    if (lower.startsWith("[") && lower.endsWith("]")) lower = lower.slice(1, -1);
    if (lower === "localhost") return true;
    if (/^\d{1,3}(\.\d{1,3}){3}$/.test(lower)) return true;
    if (/^[0-9a-f:]+$/i.test(lower) && lower.includes(":")) return true;
    const labels = lower.split(".");
    const tld = labels[labels.length - 1];
    if (/^xn--[a-z0-9-]{1,59}$/.test(tld)) return true;
    return knownTlds.has(tld);
  }
  function normalizeUrl(raw) {
    if (typeof raw !== "string") return null;
    const url = raw.trim();
    if (!url || /\s/.test(url)) return null;
    if (/^localhost(:\d+)?([/?#].*)?$/i.test(url) || /^127\.0\.0\.1(:\d+)?([/?#].*)?$/i.test(url) || /^0\.0\.0\.0(:\d+)?([/?#].*)?$/i.test(url))
      return "http://" + url;
    if (url.startsWith("//")) {
      const section = url.slice(2).split(/[/?#]/)[0];
      if (section.includes(":") && !/:\d+$/.test(section)) return null;
      try {
        const u = new URL("https:" + url);
        if (!isBareNavigableHostname(u.hostname)) return null;
        return "https:" + url;
      } catch {
        return null;
      }
    }
    const m = url.match(/^([a-zA-Z][a-zA-Z0-9+.-]*):/);
    if (!m) {
      const hostPart = url.split(/[:/?#]/)[0];
      if (!isBareNavigableHostname(hostPart)) return null;
      const hostPort = url.split(/[/?#]/)[0];
      if (hostPort.includes(":") && !/:\d+$/.test(hostPort)) return null;
      const bareTld = hostPart.toLowerCase().split(".").pop();
      if (!url.includes("/") && !url.includes(":") && !url.includes("?") && !url.includes("#") && fileExtensionDenylist.has(bareTld)) return null;
      try {
        const u = new URL("https://" + url);
        if (!isBareNavigableHostname(u.hostname)) return null;
      } catch {
        return null;
      }
      return "https://" + url;
    }
    const scheme = m[1].toLowerCase();
    if (urlSchemes.has(scheme)) {
      if (scheme === "http" || scheme === "https") {
        try {
          const u = new URL(url);
          if (u.hostname && !isValidHostname(u.hostname)) return null;
        } catch {
          return null;
        }
      }
      return url;
    }
    if (blockedUrlSchemes.has(scheme)) return null;
    const rest = url.slice(m[0].length);
    if (/^(\d+)([/?#].*)?$/.test(rest)) {
      if (!isBareNavigableHostname(m[1])) return null;
      try {
        const u = new URL("https://" + url);
        if (!isBareNavigableHostname(u.hostname)) return null;
      } catch {
        return null;
      }
      return "https://" + url;
    }
    return null;
  }

  // background/handlers.js
  function clampCount(count, max = 20) {
    const n = Math.floor(count);
    return Number.isFinite(n) ? Math.min(max, Math.max(1, n)) : 1;
  }
  async function readStoredSettings(area) {
    try {
      const stored = await chrome.storage[area].get("settings");
      if (stored && stored.settings) return stored.settings;
    } catch (err) {
      console.debug(`[jari] Failed to get ${area} settings:`, err);
    }
    return null;
  }
  async function getStoredSettings() {
    const [synced, local] = await Promise.all([
      readStoredSettings("sync"),
      readStoredSettings("local")
    ]);
    if (synced && local) {
      const syncAt = Number.isFinite(synced.updatedAt) ? synced.updatedAt : 0;
      const localAt = Number.isFinite(local.updatedAt) ? local.updatedAt : 0;
      return localAt > syncAt ? local : synced;
    }
    return synced || local || {};
  }
  async function getSuggestSettings() {
    const settings = await getStoredSettings();
    const sources = settings && settings.suggestionSources;
    return {
      sources: Array.isArray(sources) ? sources.filter((s) => suggestionSources.includes(s)) : suggestionSources.slice(),
      maxResults: settings && settings.maxResults !== void 0 ? clampMaxResults(settings.maxResults) : clampMaxResults()
    };
  }
  async function getDefaultSearchUrl(text) {
    const settings = await getStoredSettings();
    const engines = normalizeSearchEngines(settings && settings.searchEngines);
    const keyword = normalizeDefaultEngine(
      settings && settings.defaultEngine,
      engines
    );
    return buildEngineUrl(engines, keyword, text) || "https://www.google.com/search?q=" + encodeURIComponent(text);
  }
  var handlers = {
    createTab: async (_, { url } = {}) => {
      const target = url === void 0 ? void 0 : normalizeUrl(url);
      if (url !== void 0 && !target) return { ok: false };
      const tab = await chrome.tabs.create(target ? { url: target } : {});
      return tab ? { ok: true, id: tab.id } : { ok: false };
    },
    openIncognitoTab: async (_, { url } = {}) => {
      const target = url === void 0 ? void 0 : normalizeUrl(url);
      if (url !== void 0 && !target) return { ok: false };
      return openInIncognito(target);
    },
    navigate: async (sender, { url } = {}) => {
      const target = normalizeUrl(url);
      if (!target || !sender.tab || !sender.tab.id) return { ok: false };
      await chrome.tabs.update(sender.tab.id, { url: target });
      return { ok: true };
    },
    closeTab: async (sender, { count = 1 } = {}) => {
      const tab = sender.tab;
      if (!tab || !tab.id) return { ok: false };
      const tabs = await chrome.tabs.query({ currentWindow: true });
      const index = tabs.findIndex((t) => t.id === tab.id);
      if (index === -1) return { ok: false };
      const ids = tabs.slice(index, index + clampCount(count)).map((t) => t.id);
      await chrome.tabs.remove(ids);
      return { ok: true, closed: ids.length };
    },
    restoreTab: async (_, { count = 1 } = {}) => {
      let sessions;
      try {
        sessions = await chrome.sessions.getRecentlyClosed();
      } catch (err) {
        console.debug("[jari] Failed to get recently closed sessions:", err);
        return { ok: false };
      }
      const tabs = (sessions || []).filter((s) => s.tab && s.tab.sessionId);
      for (let i = 0; i < Math.min(clampCount(count), tabs.length); i++) {
        try {
          await chrome.sessions.restore(tabs[i].tab.sessionId);
        } catch {
          break;
        }
      }
      return { ok: true };
    },
    previousTab: async (sender, { count = 1 } = {}) => {
      return switchTab(sender.tab, -clampCount(count));
    },
    nextTab: async (sender, { count = 1 } = {}) => {
      return switchTab(sender.tab, clampCount(count));
    },
    moveTabToWindow: async (sender) => {
      const tab = sender.tab;
      if (!tab || !tab.id) return { ok: false };
      const myTabs = await chrome.tabs.query({ windowId: tab.windowId });
      if (myTabs.length > 1) {
        await chrome.windows.create({ tabId: tab.id });
        return { ok: true, movedToNewWindow: true };
      }
      const windows = await chrome.windows.getAll({ populate: true });
      const others = windows.filter((win) => win.id !== tab.windowId).map((win) => {
        const wtab = win.tabs && win.tabs.length ? win.tabs.find((t) => t.active) || win.tabs[0] : null;
        return {
          windowId: win.id,
          title: wtab && wtab.title ? wtab.title : "Window",
          url: `${win.tabs ? win.tabs.length : 0} tabs`
        };
      });
      if (others.length === 0) return { ok: true, needWindowChoice: false };
      if (others.length === 1) {
        await moveTabIntoWindowAndFocus(tab.id, others[0].windowId, "moveTabToWindow auto-merge");
        return { ok: true, movedToWindow: true };
      }
      return {
        ok: true,
        needWindowChoice: true,
        ownTabId: tab.id,
        ownWindowId: tab.windowId,
        tabs: others
      };
    },
    moveTabIntoWindow: async (sender, { targetWindowId } = {}) => {
      const tab = sender.tab;
      if (!tab || !tab.id || !targetWindowId) return { ok: false };
      await moveTabIntoWindowAndFocus(tab.id, targetWindowId, "moveTabIntoWindow");
      return { ok: true };
    },
    moveTabLeft: async (sender) => moveTab(sender, -1),
    goToFirstTab: async () => activateTabByIndex(0),
    goToLastTab: async () => activateTabByIndex(-1),
    moveTabRight: async (sender) => moveTab(sender, 1),
    duplicateTab: async (sender) => {
      if (sender.tab && sender.tab.id) {
        await chrome.tabs.duplicate(sender.tab.id);
        return { ok: true };
      }
      return { ok: false };
    },
    togglePin: async (sender) => {
      const tab = sender.tab;
      if (tab && tab.id) {
        await chrome.tabs.update(tab.id, { pinned: !tab.pinned });
        return { ok: true };
      }
      return { ok: false };
    },
    toggleMute: async (sender) => {
      const tab = sender.tab;
      if (tab && tab.id) {
        const muted = !!(tab.mutedInfo && tab.mutedInfo.muted);
        await chrome.tabs.update(tab.id, { muted: !muted });
        return { ok: true };
      }
      return { ok: false };
    },
    reloadTab: async (sender, { bypassCache = false } = {}) => {
      if (sender.tab && sender.tab.id) {
        await chrome.tabs.reload(sender.tab.id, { bypassCache });
        return { ok: true };
      }
      return { ok: false };
    },
    goBack: async (sender) => goHistory(sender.tab, -1),
    goForward: async (sender) => goHistory(sender.tab, 1),
    listTabs: async () => {
      const tabs = await chrome.tabs.query({});
      return tabs.map((tab) => ({
        id: tab.id,
        windowId: tab.windowId,
        title: tab.title || "",
        url: tab.url || "",
        active: !!tab.active,
        lastAccessed: tab.lastAccessed || 0,
        audible: !!tab.audible
      }));
    },
    suggest: async (_, { query = "" } = {}) => {
      const q = query.trim().toLowerCase();
      const qRaw = query.trim();
      const map = /* @__PURE__ */ new Map();
      function push(title, url, source, extra = {}) {
        if (!url) return;
        const existing = map.get(url);
        if (existing) {
          existing.visitCount = (existing.visitCount || 0) + (extra.visitCount || 0);
          existing.typedCount = (existing.typedCount || 0) + (extra.typedCount || 0);
          existing.typedVisits = (existing.typedVisits || 0) + (extra.typedVisits || 0);
          existing.lastVisit = Math.max(existing.lastVisit || 0, extra.lastVisit || 0);
          existing.lastAccessed = Math.max(existing.lastAccessed || 0, extra.lastAccessed || 0);
          if (!existing.title || existing.title === existing.url) existing.title = title || url;
          return;
        }
        map.set(url, { title: title || url, url, source, ...extra });
      }
      const { sources, maxResults } = await getSuggestSettings();
      let bookmarkFolderMap = null;
      async function getBookmarkFolderMap() {
        if (bookmarkFolderMap) return bookmarkFolderMap;
        try {
          let walk = function(nodes, path) {
            for (const node of nodes) {
              if (node.children) {
                const np = [...path, node.title].filter(Boolean);
                if (node.id) m.set(node.id, np);
                walk(node.children, np);
              } else if (node.id) {
                m.set(node.id, path);
              }
            }
          };
          const tree = await chrome.bookmarks.getTree();
          const m = /* @__PURE__ */ new Map();
          walk(tree, []);
          bookmarkFolderMap = m;
        } catch {
          bookmarkFolderMap = /* @__PURE__ */ new Map();
        }
        return bookmarkFolderMap;
      }
      if (sources.includes("tab")) {
        try {
          const tabs = await chrome.tabs.query({});
          tabs.sort((a, b) => (b.lastAccessed || 0) - (a.lastAccessed || 0));
          for (const tab of tabs) push(tab.title || "", tab.url || "", "tab", { id: tab.id, lastAccessed: tab.lastAccessed || 0, audible: !!tab.audible });
        } catch (err) {
          console.debug("[jari] Tab search failed:", err);
        }
      }
      if (!q) {
        if (sources.includes("history")) {
          try {
            const recents = await chrome.history.search({ text: "", maxResults: 24, startTime: Date.now() - 90 * 864e5 });
            recents.sort((a, b) => (b.lastVisitTime || 0) - (a.lastVisitTime || 0));
            for (const item of recents.slice(0, 12)) push(item.title, item.url, "history", { visitCount: item.visitCount || 0, lastVisit: item.lastVisitTime || 0, typedCount: item.typedCount || 0 });
          } catch (err) {
            console.debug("[jari] Recent history failed:", err);
          }
        }
        if (sources.includes("bookmark")) {
          try {
            const folderMap = await getBookmarkFolderMap();
            const bms = await chrome.bookmarks.search("");
            const withPath = bms.filter((bm) => bm.url).map((bm) => ({ bm, path: folderMap.get(bm.parentId) || [] }));
            withPath.sort((a, b) => (b.bm.dateAdded || 0) - (a.bm.dateAdded || 0));
            for (const { bm, path } of withPath.slice(0, 8)) push(bm.title, bm.url, "bookmark", { dateAdded: bm.dateAdded || 0, folderPath: path.join(" / ") });
          } catch (err) {
            console.debug("[jari] Bookmark recents failed:", err);
          }
        }
      } else {
        if (sources.includes("history")) {
          try {
            const results = await chrome.history.search({ text: qRaw, maxResults: 30, startTime: Date.now() - 90 * 864e5 });
            const top = results.slice(0, 15);
            const visitGroups = await Promise.allSettled(top.map((item) => chrome.history.getVisits ? chrome.history.getVisits({ url: item.url }).catch(() => []) : Promise.resolve([])));
            for (let i = 0; i < top.length; i++) {
              const item = top[i];
              const visits = visitGroups[i].status === "fulfilled" ? visitGroups[i].value : [];
              const typedVisits = visits.filter((v) => v.transition === "typed").length;
              push(item.title, item.url, "history", { visitCount: item.visitCount || 0, lastVisit: item.lastVisitTime || 0, typedCount: item.typedCount || 0, typedVisits });
            }
            for (const item of results.slice(15)) push(item.title, item.url, "history", { visitCount: item.visitCount || 0, lastVisit: item.lastVisitTime || 0, typedCount: item.typedCount || 0 });
          } catch (err) {
            console.debug("[jari] History search failed:", err);
          }
          try {
            const recent = await chrome.history.search({ text: "", maxResults: 100, startTime: Date.now() - 90 * 864e5 });
            for (const item of recent) push(item.title, item.url, "history", { visitCount: item.visitCount || 0, lastVisit: item.lastVisitTime || 0, typedCount: item.typedCount || 0 });
          } catch (err) {
            console.debug("[jari] Recent history pool failed:", err);
          }
        }
        if (sources.includes("bookmark")) {
          try {
            const folderMap = await getBookmarkFolderMap();
            const tree = await chrome.bookmarks.getTree();
            const stack = [...tree || []];
            while (stack.length) {
              const node = stack.pop();
              if (node.url) {
                const path = folderMap.get(node.parentId) || [];
                push(node.title, node.url, "bookmark", { dateAdded: node.dateAdded || 0, folderPath: path.join(" / ") });
              }
              if (node.children) stack.push(...node.children);
            }
          } catch (err) {
            console.debug("[jari] Bookmark search failed:", err);
          }
        }
      }
      const items = Array.from(map.values());
      return items.slice(0, maxResults);
    },
    search: async (sender, { query = "", newTab = true, incognito = false } = {}) => {
      const text = query.trim();
      if (!text) return { ok: false };
      const url = await getDefaultSearchUrl(text);
      if (incognito) {
        return openInIncognito(url);
      }
      if (newTab) {
        await chrome.tabs.create({ url });
      } else if (sender.tab && sender.tab.id) {
        await chrome.tabs.update(sender.tab.id, { url });
      }
      return { ok: true };
    },
    activateTab: async (_, { id } = {}) => {
      if (!id) return { ok: false };
      let windowId = null;
      try {
        const tab = await chrome.tabs.get(id);
        windowId = tab && tab.windowId;
      } catch {
      }
      try {
        await chrome.tabs.update(id, { active: true });
      } catch (err) {
        return { ok: false, error: String(err) };
      }
      if (windowId) {
        await focusWindow(windowId, "activateTab");
      }
      return { ok: true };
    },
    zoomBy: async (sender, { delta = 0 } = {}) => {
      const tab = sender.tab;
      if (!tab || !tab.id || typeof chrome.tabs.getZoom !== "function" || typeof chrome.tabs.setZoom !== "function") {
        return { ok: false };
      }
      const current = await chrome.tabs.getZoom(tab.id);
      const next = Math.min(5, Math.max(0.25, current + delta));
      await chrome.tabs.setZoom(tab.id, next);
      return { ok: true, zoom: next };
    },
    openInBackgroundTab: async (_, { url } = {}) => openTab(url, false),
    openInForegroundTab: async (_, { url } = {}) => openTab(url, true),
    openSettings: async () => {
      await chrome.runtime.openOptionsPage();
      return { ok: true };
    },
    openExtensions: async () => {
      const urls = ["chrome://extensions", "about:addons", "edge://extensions"];
      for (const url of urls) {
        try {
          await chrome.tabs.create({ url });
          return { ok: true };
        } catch {
        }
      }
      return { ok: false };
    }
  };
  async function goHistory(tab, delta) {
    if (!tab || !tab.id) return { ok: false };
    const method = delta < 0 ? "goBack" : "goForward";
    if (typeof chrome.tabs[method] === "function") {
      try {
        await chrome.tabs[method](tab.id);
      } catch {
        return { ok: false };
      }
    }
    return { ok: true };
  }
  async function switchTab(current, delta) {
    if (!current || !current.id) return { ok: false };
    const tabs = await chrome.tabs.query({ currentWindow: true });
    if (tabs.length < 2) return { ok: false };
    const index = tabs.findIndex((tab) => tab.id === current.id);
    if (index === -1) return { ok: false };
    const nextIndex = ((index + delta) % tabs.length + tabs.length) % tabs.length;
    await chrome.tabs.update(tabs[nextIndex].id, { active: true });
    return { ok: true };
  }
  async function openTab(url, active) {
    const target = normalizeUrl(url);
    if (!target) return { ok: false };
    await chrome.tabs.create({ url: target, active });
    return { ok: true };
  }
  async function openInIncognito(url) {
    const windows = await chrome.windows.getAll({});
    const incognito = (windows || []).find((win2) => win2 && win2.incognito);
    if (incognito) {
      const tab = await chrome.tabs.create(
        url ? { windowId: incognito.id, url, active: true } : { windowId: incognito.id, active: true }
      );
      await focusWindow(incognito.id, "openInIncognito");
      await maximizeWindow(incognito.id);
      return tab ? { ok: true, id: tab.id } : { ok: false };
    }
    const win = await chrome.windows.create(
      url ? { url, incognito: true, state: "maximized" } : { incognito: true, state: "maximized" }
    );
    return win ? { ok: true, id: win.id } : { ok: false };
  }
  async function moveTab(sender, delta) {
    const tab = sender.tab;
    if (tab && tab.id) {
      await chrome.tabs.move(tab.id, { index: Math.max(0, tab.index + delta) });
      return { ok: true };
    }
    return { ok: false };
  }
  async function activateTabByIndex(index) {
    const tabs = await chrome.tabs.query({ currentWindow: true });
    const tab = tabs[index < 0 ? tabs.length + index : index];
    if (!tab) return { ok: false };
    await chrome.tabs.update(tab.id, { active: true });
    return { ok: true };
  }
  async function moveTabIntoWindowAndFocus(tabId, targetWindowId, context) {
    await chrome.tabs.move(tabId, { windowId: targetWindowId, index: -1 });
    const tabs = await chrome.tabs.query({ windowId: targetWindowId });
    const last = tabs[tabs.length - 1];
    if (last) {
      await focusWindow(targetWindowId, context);
      await chrome.tabs.update(last.id, { active: true });
    }
  }
  async function focusWindow(windowId, context = "focusWindow") {
    try {
      const win = await chrome.windows.get(windowId);
      if (win && win.state === "minimized") {
        await chrome.windows.update(windowId, { focused: true, state: "normal" });
      } else {
        await chrome.windows.update(windowId, { focused: true });
      }
    } catch (err) {
      console.error(`[jari] ${context} window focus failed`, err);
    }
  }
  async function maximizeWindow(windowId) {
    try {
      await chrome.windows.update(windowId, { state: "maximized" });
    } catch (err) {
      console.error("[jari] openInIncognito window maximize failed", err);
    }
  }

  // background/main.js
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    const handler = handlers[message && message.action];
    if (!handler) return;
    const result = handler(sender, message || {});
    if (result && typeof result.then === "function") {
      result.then(
        (value) => sendResponse(value || { ok: true }),
        (err) => {
          console.error(`[jari] ${message.action} failed`, err);
          sendResponse({ ok: false, error: String(err) });
        }
      );
      return true;
    }
    sendResponse(result || { ok: true });
  });
})();
