// Bundles the content scripts and the options page into classic IIFE bundles
// (content scripts cannot use ES imports at runtime) and generates
// manifest.json for the target browser.
// Usage: node build.js <chrome|firefox>
import { build } from "esbuild";
import { copyFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const target = process.argv[2];
if (target !== "chrome" && target !== "firefox") {
  console.error("Usage: node build.js <chrome|firefox>");
  process.exit(1);
}

const root = join(dirname(fileURLToPath(import.meta.url)));
const contentBanner = "// Generated by build.js — do not edit. Rebuild with: node build.js <chrome|firefox>\n";
const optionsBanner = "// Generated by build.js — do not edit.\n";

// content/bundle.js is the content-script entry: it imports the feature
// modules, so esbuild resolves the dependency graph instead of the previous
// hardcoded concatenation order.
await build({
  entryPoints: [join(root, "content", "content.js")],
  bundle: true,
  format: "iife",
  outfile: join(root, "content", "bundle.js"),
  banner: { js: contentBanner },
  logLevel: "warning",
});

// options/options.bundle.js is the options-page script. It imports the same
// modules for its own UI (settings, commands, keymap helpers); the page also
// loads content/bundle.js so Jari's content features work on it.
await build({
  entryPoints: [join(root, "options", "options.js")],
  bundle: true,
  format: "iife",
  outfile: join(root, "options", "options.bundle.js"),
  banner: { js: optionsBanner },
  logLevel: "warning",
});

const src = join(root, `manifest.${target}.json`);
const dest = join(root, "manifest.json");
if (!existsSync(src)) {
  console.error(`Missing source manifest: ${src}`);
  process.exit(1);
}
copyFileSync(src, dest);

console.log("Wrote content/bundle.js");
console.log("Wrote options/options.bundle.js");
console.log(`Wrote manifest.json from manifest.${target}.json`);
console.log(`Load this folder in ${target === "chrome" ? "Chrome" : "Firefox"}.`);
