import { execFileSync } from "node:child_process";
import { build } from "esbuild";
import {
  copyFileSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const target = process.argv[2];
if (target !== "chrome" && target !== "firefox" && target !== "dist") {
  console.error("Usage: node build.js <chrome|firefox|dist>");
  process.exit(1);
}

const root = join(dirname(fileURLToPath(import.meta.url)));
const buildBanner =
  "// Generated by build.js — do not edit. Rebuild with: node build.js <chrome|firefox>\n";

// Runtime files staged for the release artifacts (zips, xpi, crx).
const distFiles = [
  "background.js",
  "LICENSE",
  "content/bundle.js",
  "content/content.css",
  "options/options.html",
  "options/options.bundle.js",
  "options/options.css",
  "icons/icon-16.png",
  "icons/icon-32.png",
  "icons/icon-48.png",
  "icons/icon-128.png",
];

await buildOne("content", "content.js", "bundle.js", buildBanner);
await buildOne("options", "options.js", "options.bundle.js", buildBanner);
await buildOne("background", "main.js", "background.js", buildBanner);

console.log("Wrote content/bundle.js");
console.log("Wrote options/options.bundle.js");
console.log("Wrote background.js");

if (target === "dist") {
  buildDist("chrome");
  buildDist("firefox");
} else {
  writeFileSync(
    join(root, "manifest.json"),
    JSON.stringify(manifestFor(target), null, 2) + "\n",
  );
  console.log(`Wrote manifest.json (${target})`);
  console.log(
    `Load this folder in ${target === "chrome" ? "Chrome" : "Firefox"}.`,
  );
}

function manifestFor(target) {
  const manifest = JSON.parse(
    readFileSync(join(root, "manifest.base.json"), "utf8"),
  );
  if (target === "chrome") {
    manifest.background = { service_worker: "background.js" };
    delete manifest.browser_specific_settings;
  } else {
    manifest.background = { scripts: ["background.js"] };
    manifest.permissions.push("clipboardWrite");
  }
  return manifest;
}

function buildDist(target) {
  const manifest = manifestFor(target);
  const stage = join(root, "dist", `jari-${target}`);
  rmSync(stage, { recursive: true, force: true });
  for (const file of distFiles) {
    mkdirSync(join(stage, dirname(file)), { recursive: true });
    copyFileSync(join(root, file), join(stage, file));
  }
  writeFileSync(join(stage, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  if (target === "firefox") {
    buildFirefoxXpi(stage, manifest.version);
  } else {
    buildChromeZip(stage, manifest.version);
    packChromeCrx(stage, manifest.version);
  }
}

function crxKeyPem() {
  const raw = String(process.env.CRX_PRIVATE_KEY || "");
  if (!raw.trim()) return null;
  const decoded = Buffer.from(raw.replace(/\s+/g, ""), "base64").toString(
    "utf8",
  );
  if (decoded.includes("PRIVATE KEY")) return decoded;
  if (raw.includes("PRIVATE KEY")) return raw;
  throw new Error(
    "CRX_PRIVATE_KEY must be the base64 output of `base64 -w0 key.pem` (or the .pem text itself)",
  );
}

function runNodeBin(bin, args) {
  execFileSync(process.execPath, [bin, ...args], { stdio: "inherit" });
}

function buildFirefoxXpi(stage, version) {
  const webExt = join(root, "node_modules", "web-ext", "bin", "web-ext.js");
  runNodeBin(webExt, ["lint", "--source-dir", stage]);
  const zip = join(root, "dist", `jari-${version}.zip`);
  rmSync(zip, { force: true });
  runNodeBin(webExt, [
    "build",
    "--source-dir",
    stage,
    "--artifacts-dir",
    join(root, "dist"),
    "--overwrite-dest",
  ]);
  const xpi = join(root, "dist", `jari-firefox-${version}.xpi`);
  rmSync(xpi, { force: true });
  renameSync(zip, xpi);
  console.log(`Wrote ${xpi}`);
}

function buildChromeZip(stage, version) {
  const zip = join(root, "dist", `jari-chrome-${version}.zip`);
  rmSync(zip, { force: true });
  execFileSync("zip", ["-qr", zip, "."], { cwd: stage });
  console.log(`Wrote ${zip}`);
}

function packChromeCrx(stage, version) {
  const pem = crxKeyPem();
  if (!pem) {
    console.log("Skipping CRX pack (CRX_PRIVATE_KEY not set)");
    return;
  }
  const keyFile = join(tmpdir(), `jari-crx-key-${process.pid}.pem`);
  writeFileSync(keyFile, pem, { mode: 0o600 });
  try {
    const crx = join(root, "dist", `jari-chrome-${version}.crx`);
    rmSync(crx, { force: true });
    runNodeBin(join(root, "node_modules", "crx3", "bin", "crx3.js"), [
      stage,
      "-o",
      crx,
      "-p",
      keyFile,
    ]);
  } finally {
    rmSync(keyFile, { force: true });
  }
}

async function buildOne(dir, entry, outfile, banner) {
  const outPath = join(root, dir === "background" ? "." : dir, outfile);
  await build({
    entryPoints: [join(root, dir, entry)],
    bundle: true,
    format: "iife",
    outfile: outPath,
    banner: { js: banner },
    logLevel: "warning",
  });

  const firstLine = readFileSync(outPath, "utf8").split("\n", 1)[0];
  if (firstLine !== buildBanner.trim()) {
    throw new Error(`Banner missing from ${outPath}`);
  }
}
