import { build } from "esbuild";
import { copyFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const target = process.argv[2];
if (target !== "chrome" && target !== "firefox") {
  console.error("Usage: node build.js <chrome|firefox>");
  process.exit(1);
}

const root = join(dirname(fileURLToPath(import.meta.url)));
const buildBanner =
  "// Generated by build.js — do not edit. Rebuild with: node build.js <chrome|firefox>\n";

await buildOne("content", "content.js", "bundle.js", buildBanner);
await buildOne(
  "options",
  "options.js",
  "options.bundle.js",
  "// Generated by build.js — do not edit.\n",
);
await buildOne("background", "main.js", "background.js", buildBanner);

const src = join(root, `manifest.${target}.json`);
const dest = join(root, "manifest.json");
if (!existsSync(src)) {
  console.error(`Missing source manifest: ${src}`);
  process.exit(1);
}
copyFileSync(src, dest);

console.log("Wrote content/bundle.js");
console.log("Wrote options/options.bundle.js");
console.log("Wrote background.js");
console.log(`Wrote manifest.json from manifest.${target}.json`);
console.log(
  `Load this folder in ${target === "chrome" ? "Chrome" : "Firefox"}.`,
);

async function buildOne(dir, entry, outfile, banner) {
  const outPath = join(root, dir === "background" ? "." : dir, outfile);
  await build({
    entryPoints: [join(root, dir, entry)],
    bundle: true,
    format: "iife",
    outfile: outPath,
    banner: { js: banner },
    logLevel: "warning",
  });

  const firstLine = readFileSync(outPath, "utf8").split("\n", 1)[0];
  if (!firstLine.startsWith("//")) {
    throw new Error(`Banner missing from ${outPath}`);
  }
}
