export const COMMAND_CATALOG = {

  scrollDown: { category: "scrolling", label: "Scroll down", repeatable: true },
  scrollUp: { category: "scrolling", label: "Scroll up", repeatable: true },
  scrollLeft: { category: "scrolling", label: "Scroll left", repeatable: true },
  scrollRight: { category: "scrolling", label: "Scroll right", repeatable: true },
  scrollToTop: { category: "scrolling", label: "Scroll to top" },
  scrollToBottom: { category: "scrolling", label: "Scroll to bottom" },
  scrollPageDown: { category: "scrolling", label: "Scroll page down", repeatable: true },
  scrollPageUp: { category: "scrolling", label: "Scroll page up", repeatable: true },
  scrollHalfPageDown: { category: "scrolling", label: "Scroll half page down", repeatable: true },
  scrollHalfPageUp: { category: "scrolling", label: "Scroll half page up", repeatable: true },
  cycleScrollFrame: { category: "scrolling", label: "Cycle scroll area / frame" },

  zoomIn: { category: "zoom", label: "Zoom in" },
  zoomOut: { category: "zoom", label: "Zoom out" },

  newTab: { category: "tabs", label: "New tab" },
  newIncognitoTab: { category: "tabs", label: "New incognito tab" },
  closeTab: { category: "tabs", label: "Close tab", repeatable: true },
  restoreTab: { category: "tabs", label: "Reopen closed tab", repeatable: true },
  previousTab: { category: "tabs", label: "Previous tab", repeatable: true },
  nextTab: { category: "tabs", label: "Next tab", repeatable: true },
  goToFirstTab: { category: "tabs", label: "Go to first tab" },
  goToLastTab: { category: "tabs", label: "Go to last tab" },
  openOmnibar: { category: "tabs", label: "Open URL or search" },
  openOmnibarIncognito: { category: "tabs", label: "Open URL or search in incognito" },
  openClipboard: { category: "tabs", label: "Open clipboard URL in this tab" },
  openClipboardBackground: { category: "tabs", label: "Open clipboard URL in background tab" },
  duplicateTab: { category: "tabs", label: "Duplicate tab" },
  moveTabLeft: { category: "tabs", label: "Move tab left" },
  moveTabRight: { category: "tabs", label: "Move tab right" },
  togglePin: { category: "tabs", label: "Pin / unpin tab" },
  toggleMute: { category: "tabs", label: "Mute / unmute tab" },
  moveTabToWindow: { category: "tabs", label: "Move tab to another window" },

  goBack: { category: "history", label: "Go back in history" },
  goForward: { category: "history", label: "Go forward in history" },

  reloadTab: { category: "page", label: "Reload tab" },
  forceReload: { category: "page", label: "Reload without cache" },
  goToParent: { category: "page", label: "Go to parent page" },
  goToRoot: { category: "page", label: "Go to site root" },
  editUrl: { category: "page", label: "Edit current URL" },
  copyUrl: { category: "page", label: "Copy page URL" },
  copyTitleAndUrl: { category: "page", label: "Copy title + URL" },

  toggleIgnore: { category: "modes", label: "Ignore mode" },
  passthroughKeys: { category: "modes", label: "Passthrough keys (timed)" },
  toggleSiteEnabled: { category: "modes", label: "Enable / disable on this site" },

  hintClick: { category: "hints", label: "Click link" },
  hintOpen: { category: "hints", label: "Open link in new tab" },
  hintOpenBackground: { category: "hints", label: "Open link in background tab" },
  hintInput: { category: "hints", label: "Focus input" },
  hintYank: { category: "hints", label: "Copy link URL" },

  findText: { category: "find", label: "Find in page" },
  findNext: { category: "find", label: "Next match", repeatable: true },
  findPrev: { category: "find", label: "Previous match", repeatable: true },

  enterVisual: { category: "visual", label: "Visual mode" },
  enterVisualLine: { category: "visual", label: "Visual line mode" },

  showHelp: { category: "help", label: "Show this help" },
  openSettings: { category: "help", label: "Open settings" },
  openExtensions: { category: "help", label: "Open extensions page" },
};
